version: "3"
services:

  haproxy:
    image: haproxy:lts-alpine
    container_name: dwc_haproxy
    network_mode: "service:wireguard"
    restart: unless-stopped
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    sysctls:
     - net.ipv4.ip_unprivileged_port_start=0

  dwc:
    build: .
    container_name: dwc_server
    network_mode: "service:wireguard"
    restart: unless-stopped
    volumes:
      - data:/dwc/data
  
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=geese.jbritain.net #optional
      - SERVERPORT=51820 #optional
      - PEERS=15 #optional
 #     - PEERDNS= #optional
      - INTERNAL_SUBNET=10.64.84.0 #optional
      - ALLOWEDIPS=10.64.84.0/24, 172.64.84.0/24 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      static-network:
        ipv4_address: 172.64.84.4
    restart: unless-stopped

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.64.0.0/16

volumes:
  data:
